apiVersion: 1
datasources:
  - name: InfluxDB-k6
    type: influxdb
    uid: influxdb-k6
    access: proxy
    url: http://influxdb:8086
    database: k6
    isDefault: true
    jsonData:
      httpMode: GET

  - name: Prometheus
    type: prometheus
    uid: prometheus-main
    access: proxy
    url: http://prometheus:9090
    jsonData:
      timeInterval: "5s"
